#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : liborcus
Version  : 0.13.4
Release  : 1
URL      : https://dev-www.libreoffice.org/src/liborcus-0.13.4.tar.gz
Source0  : https://dev-www.libreoffice.org/src/liborcus-0.13.4.tar.gz
Summary  : Standalone file import filter library for spreadsheet documents.
Group    : Development/Tools
License  : MPL-2.0
Requires: liborcus-bin
Requires: liborcus-python3
Requires: liborcus-lib
Requires: liborcus-license
Requires: liborcus-python
BuildRequires : boost-dev
BuildRequires : ixion-dev
BuildRequires : pkgconfig(mdds-1.2)
BuildRequires : pkgconfig(python3)
BuildRequires : pkgconfig(zlib)

%description
Orcus - library for processing spreadsheet documents.
=====================================================

%package bin
Summary: bin components for the liborcus package.
Group: Binaries
Requires: liborcus-license

%description bin
bin components for the liborcus package.


%package dev
Summary: dev components for the liborcus package.
Group: Development
Requires: liborcus-lib
Requires: liborcus-bin
Provides: liborcus-devel

%description dev
dev components for the liborcus package.


%package lib
Summary: lib components for the liborcus package.
Group: Libraries
Requires: liborcus-license

%description lib
lib components for the liborcus package.


%package license
Summary: license components for the liborcus package.
Group: Default

%description license
license components for the liborcus package.


%package python
Summary: python components for the liborcus package.
Group: Default
Requires: liborcus-python3

%description python
python components for the liborcus package.


%package python3
Summary: python3 components for the liborcus package.
Group: Default
Requires: python3-core

%description python3
python3 components for the liborcus package.


%prep
%setup -q -n liborcus-0.13.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534615855
%configure --disable-static --without-gnumeric-filter --disable-spreadsheet-model
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1534615855
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/liborcus
cp LICENSE %{buildroot}/usr/share/doc/liborcus/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/orcus-css-dump
/usr/bin/orcus-detect
/usr/bin/orcus-json
/usr/bin/orcus-mso-encryption
/usr/bin/orcus-xml-dump
/usr/bin/orcus-yaml
/usr/bin/orcus-zip-dump

%files dev
%defattr(-,root,root,-)
/usr/include/liborcus-0.13/orcus/base64.hpp
/usr/include/liborcus-0.13/orcus/cell_buffer.hpp
/usr/include/liborcus-0.13/orcus/config.hpp
/usr/include/liborcus-0.13/orcus/css_document_tree.hpp
/usr/include/liborcus-0.13/orcus/css_parser.hpp
/usr/include/liborcus-0.13/orcus/css_parser_base.hpp
/usr/include/liborcus-0.13/orcus/css_selector.hpp
/usr/include/liborcus-0.13/orcus/css_types.hpp
/usr/include/liborcus-0.13/orcus/csv_parser.hpp
/usr/include/liborcus-0.13/orcus/csv_parser_base.hpp
/usr/include/liborcus-0.13/orcus/detail/parser_token_buffer.hpp
/usr/include/liborcus-0.13/orcus/detail/thread.hpp
/usr/include/liborcus-0.13/orcus/dom_tree.hpp
/usr/include/liborcus-0.13/orcus/env.hpp
/usr/include/liborcus-0.13/orcus/exception.hpp
/usr/include/liborcus-0.13/orcus/format_detection.hpp
/usr/include/liborcus-0.13/orcus/global.hpp
/usr/include/liborcus-0.13/orcus/info.hpp
/usr/include/liborcus-0.13/orcus/interface.hpp
/usr/include/liborcus-0.13/orcus/json_document_tree.hpp
/usr/include/liborcus-0.13/orcus/json_global.hpp
/usr/include/liborcus-0.13/orcus/json_parser.hpp
/usr/include/liborcus-0.13/orcus/json_parser_base.hpp
/usr/include/liborcus-0.13/orcus/json_parser_thread.hpp
/usr/include/liborcus-0.13/orcus/measurement.hpp
/usr/include/liborcus-0.13/orcus/mso/encryption_info.hpp
/usr/include/liborcus-0.13/orcus/orcus_csv.hpp
/usr/include/liborcus-0.13/orcus/orcus_import_ods.hpp
/usr/include/liborcus-0.13/orcus/orcus_import_xlsx.hpp
/usr/include/liborcus-0.13/orcus/orcus_ods.hpp
/usr/include/liborcus-0.13/orcus/orcus_xls_xml.hpp
/usr/include/liborcus-0.13/orcus/orcus_xlsx.hpp
/usr/include/liborcus-0.13/orcus/orcus_xml.hpp
/usr/include/liborcus-0.13/orcus/parser_base.hpp
/usr/include/liborcus-0.13/orcus/parser_global.hpp
/usr/include/liborcus-0.13/orcus/pstring.hpp
/usr/include/liborcus-0.13/orcus/sax_ns_parser.hpp
/usr/include/liborcus-0.13/orcus/sax_parser.hpp
/usr/include/liborcus-0.13/orcus/sax_parser_base.hpp
/usr/include/liborcus-0.13/orcus/sax_token_parser.hpp
/usr/include/liborcus-0.13/orcus/sax_token_parser_thread.hpp
/usr/include/liborcus-0.13/orcus/spreadsheet/export_interface.hpp
/usr/include/liborcus-0.13/orcus/spreadsheet/import_interface.hpp
/usr/include/liborcus-0.13/orcus/spreadsheet/import_interface_pivot.hpp
/usr/include/liborcus-0.13/orcus/spreadsheet/import_interface_view.hpp
/usr/include/liborcus-0.13/orcus/spreadsheet/types.hpp
/usr/include/liborcus-0.13/orcus/spreadsheet/view_types.hpp
/usr/include/liborcus-0.13/orcus/stream.hpp
/usr/include/liborcus-0.13/orcus/string_pool.hpp
/usr/include/liborcus-0.13/orcus/threaded_json_parser.hpp
/usr/include/liborcus-0.13/orcus/threaded_sax_token_parser.hpp
/usr/include/liborcus-0.13/orcus/tokens.hpp
/usr/include/liborcus-0.13/orcus/types.hpp
/usr/include/liborcus-0.13/orcus/xml_namespace.hpp
/usr/include/liborcus-0.13/orcus/xml_structure_tree.hpp
/usr/include/liborcus-0.13/orcus/yaml_document_tree.hpp
/usr/include/liborcus-0.13/orcus/yaml_parser.hpp
/usr/include/liborcus-0.13/orcus/yaml_parser_base.hpp
/usr/include/liborcus-0.13/orcus/zip_archive.hpp
/usr/include/liborcus-0.13/orcus/zip_archive_stream.hpp
/usr/lib64/liborcus-0.13.so
/usr/lib64/liborcus-mso-0.13.so
/usr/lib64/liborcus-parser-0.13.so
/usr/lib64/pkgconfig/liborcus-0.13.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/liborcus-0.13.so.0
/usr/lib64/liborcus-0.13.so.0.0.0
/usr/lib64/liborcus-mso-0.13.so.0
/usr/lib64/liborcus-mso-0.13.so.0.0.0
/usr/lib64/liborcus-parser-0.13.so.0
/usr/lib64/liborcus-parser-0.13.so.0.0.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/liborcus/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
